config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  authenticate :user, lambda { |u| u.role?(:admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end

  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '(:locale)' do
    resources :checkout, only: %i[show edit update]
    resources :order_items, only: %i[create update destroy]
    resources :carts, only: %i[show update]
    resources :orders, only: %i[index show]
    resource :product, only: %i[show] do
      resources :comments, only: %i[index create]
    end
    resources :settings, only: %i[index create destroy]
    resource :settings, only: %i[update] do
      collection do
        patch 'update_password'
      end
    end

    root 'pages#home', as: 'store', via: :all

    get '/', to: 'pages#home', as: 'home'
    get '/catalog', to: 'pages#catalog', as: 'catalog'
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  before_action :authenticate_user!

  ORDER_STATE = { cart: :cart,
                  address: :address,
                  delivery: :delivery_method,
                  payment: :payment,
                  confirmation: :confirmation }.freeze

  def index
    @orders = Order.sort_order(current_user.id, params[:sort_order])
  end

  def show
    @result = Checkout::ShowOrder.call(params)
    set_instance
    render params[:next_render].to_sym
    set_in_queued
  end

  def update # rubocop:disable Metrics/AbcSize
    session[:check] = params[:check]
    @result = Checkout::UpdateOrder.call(params)
    set_instance
    if @result.failure?
      render @result.render.to_sym
    else
      redirect_to checkout_path(next_render: params[:next_render].to_sym)
    end
  end

  private

  def set_instance
    @billing_address = @result.billing_address
    @shipping_address = @result.shipping_address
    @delivery = @result.delivery
    @card = @result.card
  end

  def set_in_queued
    @order.add_in_queued! if @order.state == 'complete'
  end
end

app/views/checkout/_address_form.html.haml
= fields_for address_type, address do |f|
  - address = @billing_address if address_type == AddressForm::ADDRESS_TYPE[:billing]
  - address = @shipping_address if address_type == AddressForm::ADDRESS_TYPE[:shipping]
  .form-group{class: "#{"has-error" if adress_has_error?(address, :first_name)}"}
    = f.label :first_name, t('.first_name'), { class: 'control-label font-weight-lights', for: "first_name" }
    = f.text_field :first_name, { class: 'form-control', id: 'firstName', type: "text", placeholder: "First Name" }
    %span.help-block= adress_error_message(address, :first_name) if address.errors.any?
  .form-group{class: "#{"has-error" if adress_has_error?(address, :last_name)}"}
    = f.label :last_name, t('.last_name'), { class: 'control-label font-weight-lights', for: "last_name" }
    = f.text_field :last_name, { class: 'form-control', id: 'lastName', type: "text", placeholder: "Last Name" }
    %span.help-block= adress_error_message(address, :last_name) if address.errors.any?
  .form-group{class: "#{"has-error" if adress_has_error?(address, :address)}"}
    = f.label :address, t('.address'), { class: 'control-label font-weight-lights', for: "address" }
    = f.text_field :address, { class: 'form-control', id: 'address', type: "text", placeholder: "Address" }
    %span.help-block= adress_error_message(address, :address) if address.errors.any?
  .form-group{class: "#{"has-error" if adress_has_error?(address, :city)}"}
    = f.label :city, t('.city'), { class: 'control-label font-weight-lights', for: "city" }
    = f.text_field :city, { class: 'form-control', id: 'city', type: "text", placeholder: "City" }
    %span.help-block= adress_error_message(address, :city) if address.errors.any?
  .form-group{class: "#{"has-error" if adress_has_error?(address, :zip)}"}
    = f.label :zip, t('.zip'), { class: 'control-label font-weight-lights', for: "zip" }
    = f.text_field :zip, { class: 'form-control', id: 'zip', type: "text", placeholder: "Zip" }
    %span.help-block= adress_error_message(address, :zip) if address.errors.any?
  .form-group{class: "#{"has-error" if adress_has_error?(address, :country)}"}
    = f.label :country, t('.country'), { class: 'control-label font-weight-lights', for: "country" }
    = f.text_field :country, { class: 'form-control', id: 'country', type: "text", placeholder: "Country" }
    %span.help-block= adress_error_message(address, :country) if address.errors.any?
  .form-group{class: "#{"has-error" if adress_has_error?(address, :phone)}"}
    = f.label :phone, t('.phone'), { class: 'control-label font-weight-lights', for: "phone" }
    = f.text_field :phone, { class: 'form-control', id: 'phone', type: "tel", placeholder: "Example +355 66 123 4567" }
    %span.help-block= adress_error_message(address, :phone) if address.errors.any?
    - if order
      = f.text_field :order_id, { id: 'checkbox-input', hidden: "true", value: @order.id }
    = f.text_field :user_id, { id: 'checkbox-input', hidden: "true", value: current_user.id }
    = f.text_field :address_type, { id: 'checkbox-input', hidden: "true", value: address_type}

app/views/checkout/address.html.haml
%h1.general-title-margin= t('.checkout')
%ul.steps.list-inline
  %li.step.active
    %span.step-number 1
    %span.step-text.hidden-xs= t('.address')
  %li.step-divider
  %li.step
    %span.step-number 2
    %span.step-text.hidden-xs= t('.delivery')
  %li.step-divider
  %li.step
    %span.step-number 3
    %span.step-text.hidden-xs= t('.payment')
  %li.step-divider
  %li.step
    %span.step-number 4
    %span.step-text.hidden-xs= t('.confirm')
  %li.step-divider
  %li.step
    %span.step-number 5
    %span.step-text.hidden-xs= t('.complete')
= form_for @billing_address, :url => checkout_path(user_id: current_user, step: :address, next_render: :delivery), :method => :put, :html => {:id => "form1"} do |f|
  .hidden-xs.hidden-sm
    .row
      .col-md-5 
        %h3.general-subtitle= t('.billing_address')
        %p.general-info-text= t('.all_fields_are_required')
      .col-md-5.col-md-offset-1
        %h3.general-subtitle= t('.shipping_address')
        %p.general-info-text= t('address.all_fields_required')
  .row
    .col-md-5.mb-40
      = render 'address_form', address: @billing_address, address_type: :billing, order: true
    .col-md-5.col-md-offset-1.mb-60#form2{style: "#{'display: none;' if check?}" }
      = render 'address_form', address: @shipping_address, address_type: :shipping, order: true
    .col-md-5.mb-40
    .col-md-5.col-md-offset-1.mb-60
      .form-group.checkbox
        %label.checkbox-label
          = check_box_tag "check", "true", false, class: "checkbox-input", checked: check?, onchange: "document.getElementById('form2').style.display = this.checked ? 'none' : 'block'"
          %span.checkbox-text= t('.use_billing_adress')
  .general-text-align.mb-60
    %p.in-gold-500.font-18= t('order_summary')
    %table.general-summary-table
      %tr
        %td
          %p.font-16= t('.item_total')
        %td
          %p.font-16= number_to_currency(@order.total_price)
      %tr
        %td
          %p.font-16= t('.order_total')
        %td
          %p.font-16= number_to_currency(@order.total_price - @order.coupon&.price.to_i)
    = f.submit I18n.t('save_and_continue'), { class: 'btn center-block mb-20' }

app/views/checkout/complete.html.haml
%h1.general-title-margin= t('.checkout')
%ul.steps.list-inline
  %li.step.active
    %span.step-number
      %i.fa.fa-check.step-icon
    %span.step-text.hidden-xs= t('.address')
  %li.step-divider
  %li.step.active
    %span.step-number
      %i.fa.fa-check.step-icon
    %span.step-text.hidden-xs= t('.delivery')
  %li.step-divider
  %li.step.active
    %span.step-number
      %i.fa.fa-check.step-icon
    %span.step-text.hidden-xs= t('.payment')
  %li.step-divider
  %li.step.active
    %span.step-number
      %i.fa.fa-check.step-icon
    %span.step-text.hidden-xs= t('.confirm')
  %li.step-divider
  %li.step.active
    %span.step-number 5
    %span.step-text.hidden-xs= t('.complete')
.text-center.mb-40
  %h3.general-subtitle= t('.thank')
  %p.font-weight-light= t('.an_order, email: current_user.email')
.row.mb-20
  .col-sm-6
    .visible-xs
      %p.general-order-number.mb-0= @order.number
      %p.general-address.mb-30= @order.shipping_address
    %p.general-address
      = @order.shipping_name
      %br
      = @order.shipping_address
      %br
      = @order.shipping_city
      %br
      = @order.shipping_country
      %br
      = @order.shipping_phone
  .col-sm-6.hidden-xs.text-right
    %p.general-order-number.mb-0= @order.number
    %p.general-address.mb-30= @order.date
.hidden-xs.divider-lg.pt-20
  %table.table.table-hover
    %thead
      %tr
        %th
          %span.in-grey-600= t('.book')
        %th.col-method
        %th
          %span.in-grey-600= t('.price')
        %th
          %span.in-grey-600= t('.quantity')
        %th
          %span.in-grey-600= t('.total') 
    - @order.order_items.each do |item|
      %tbody
        %tr
          %td
            .general-img-wrap-table
              %img.cart-img-shadow.pull-left.width-full{src: item.product.covers.first.image_url}
          %td
            %p.general-title= item.product.title
            %p.in-grey-600.font-weight-light= item.product.title
          %td
            %span.font-16.in-gold-500= "€#{item.product.price}"
          %td
            %span.ml-30= item.quantity
          %td
            %span.font-16.in-gold-500= number_to_currency(item.total_price)
.text-center.general-text-right
  %p.in-gold-500.font-18= t('.order_summary')
  %table.general-summary-table.general-summary-table-right.general-text-right
    %tr
      %td
        %p.font-16= t('.subtotal') 
      %td
        %p.font-16= number_to_currency(@order.subtotal)
    %tr
      %td
        %p.font-16= t('.coupon') 
      %td
        %p.font-16= number_to_currency(@order.coupon&.price.to_i)
    %tr
      %td
        %strong.font-18= t('.order_total')
      %td
        %strong.font-18= number_to_currency(@order.total_price + @order.delivery.price - @order.coupon&.price.to_i)
.text-center
  = button_to t('.back_to_store'), home_path, method: :get, class: 'btn btn-default mb-20'

app/views/checkout/confirmation.html.haml
%h1.general-title-margin= t('.checkout')
%ul.steps.list-inline
  %li.step.active
    %span.step-number
      %i.fa.fa-check.step-icon
    %span.step-text.hidden-xs= t('.address')
  %li.step-divider
  %li.step.active
    %span.step-number
      %i.fa.fa-check.step-icon
    %span.step-text.hidden-xs= t('.delivery')
  %li.step-divider
  %li.step.active
    %span.step-number
      %i.fa.fa-check.step-icon
    %span.step-text.hidden-xs= t('.payment')
  %li.step-divider
  %li.step.active
    %span.step-number 4
    %span.step-text.hidden-xs= t('.confirm')
  %li.step-divider
  %li.step
    %span.step-number 5
    %span.step-text.hidden-xs= t('.complete')
.row.mb-20
  .col-sm-3
    %h3.general-subtitle= t('.shipping_address')
    %p.general-address
      = @order.shipping_name
      %span.general-edit= link_to t('.edit'), checkout_path(user_id: current_user, next_render: :address, step: :address), method: :get, class: 'general-edit'
      %br
      = @order.shipping_address
      %br
      = @order.shipping_city
      %br
      = @order.shipping_country
      %br
      = @order.shipping_phone
  .col-sm-3
    %h3.general-subtitle= t('.billing_address')
    %p.general-address
      = @order.billing_name
      %span.general-edit= link_to t('.edit'), checkout_path(user_id: current_user, next_render: :address, step: :address), method: :get, class: 'general-edit' 
      %br
      = @order.billing_address
      %br
      = @order.billing_city
      %br
      = @order.billing_country
      %br
      = @order.billing_phone
  .col-sm-3
    %h3.general-subtitle= t('.shipments')
    %p.general-address
      = "Delivery #{@order.delivery.days} Days"
      %span.general-edit= link_to t('.edit'), checkout_path(user_id: current_user, step: :address, next_render: :delivery), method: :get, class: 'general-edit' 
      %br
      = @order.delivery.method
  .col-sm-3
    %h3.general-subtitle= t('.payment_information')
    %p.general-address
      = @order.safe_card_number
      %span.general-edit= link_to t('.edit'), checkout_path(step: :delivery_method, next_render: :payment), method: :get, class: 'general-edit' 
      %br
      = @order.card&.mm_yy
.hidden-xs.divider-lg.pt-20
  %table.table.table-hover
    %thead
      %tr
        %th
          %span.in-grey-600= t('.book')
        %th.col-method
        %th
          %span.in-grey-600= t('.price')
        %th
          %span.in-grey-600= t('.quantity')
        %th
          %span.in-grey-600= t('.total') 
    - @order.order_items.each do |item|
      %tbody
        %tr
          %td
            .general-img-wrap-table
              %img.cart-img-shadow.pull-left.width-full{src: item.product.covers.first.image_url}
          %td
            %p.general-title= item.product.title
            %p.in-grey-600.font-weight-light= item.product.title
          %td
            %span.font-16.in-gold-500= "€#{item.product.price}"
          %td
            %span.ml-30= item.quantity
          %td
            %span.font-16.in-gold-500= number_to_currency(item.total_price)
.text-center.general-text-right
  %p.in-gold-500.font-18= t('.order_summary')
  %table.general-summary-table.general-summary-table-right.general-text-right
    %tr
      %td
        %p.font-16= t('.subtotal')
      %td
        %p.font-16= number_to_currency(@order.total_price + @order.delivery.price)
    %tr
      %td
        %p.font-16= t('.coupon') 
      %td
        %p.font-16= number_to_currency(@order.coupon&.price.to_i)
    %tr
      %td
        %strong.font-18= t('.order_total')
      %td
        %strong.font-18= number_to_currency(@order.total_price + @order.delivery.price - @order.coupon&.price.to_i)
.text-center
  = button_to "Place Order", checkout_path(complete: true, step: :confirmation, next_render: :complete), method: :patch, class: 'btn btn-default mb-20'

app/views/checkout/delivery.html.haml
%h1.general-title-margin= t('.checkout')
%ul.steps.list-inline
  %li.step
    %span.step-number 1
    %span.step-text.hidden-xs= t('.address')
  %li.step-divider
  %li.step.active
    %span.step-number 2
    %span.step-text.hidden-xs= t('.delivery')
  %li.step-divider
  %li.step
    %span.step-number 3
    %span.step-text.hidden-xs= t('.payment')
  %li.step-divider
  %li.step
    %span.step-number 4
    %span.step-text.hidden-xs= t('.confirm')
  %li.step-divider
  %li.step
    %span.step-number 5
    %span.step-text.hidden-xs= t('.complete')
%h3.general-subtitle= t('.credit_card')
.visible-xs
.hidden-xs.mb-res-50
  %table.table.table-hover
    %thead
      %tr
        %th.col-method
          %span.in-grey-600.ml-40= t('.method')
        %th
          %span.in-grey-600= t('.days')
        %th
          %span.in-grey-600= t('.price')
    %tbody
    = form_for @delivery, :url => checkout_path(step: :delivery_method, next_render: :payment), :method => :put do |f|
      %tr
        %td
          .form-group.radio.mt-0.mb-0
            = f.radio_button :id, '2', { :class => 'radio-icon radio-text text-center radio-input', :style => 'margin-left: 5px;', :checked => true }
            = f.label :delivery, 'Regular Delivery', :value => '2', :class => 'font-16 font-weight-light pl-0', :style => 'margin-left: 50px;'
        %td
          %span 3 days
        %td
          %span.font-16.in-gold-500 €10.00
      %tr
        %td
          .form-group.radio.mt-0.mb-0
            %label.font-16.font-weight-light.pl-0
              = f.radio_button :id, '1', { :class => 'radio-icon radio-text text-center radio-input', :style => 'margin-left: 5px;' }
              = f.label :delivery, 'Express Delivery', :value => '1', :class => 'font-16 font-weight-light pl-0', :style => 'margin-left: 50px;'
        %td
          %span 1 days
        %td
          %span.font-16.in-gold-500 €20.00
      .general-text-align
        %table.general-summary-table
          %tr
            %td
              %p.font-16= t('.subtotal')
            %td
              %p.font-16= number_to_currency(@order.total_price)
          %tr
            %td
              %p.font-16= t('.coupon') 
            %td
              %p.font-16= number_to_currency(@order.coupon&.price.to_i)
          %tr
            %td
              %strong.font-18= t('.order_total')
            %td
              %strong.font-18= number_to_currency(@order.total_price - @order.coupon&.price.to_i)
      .text-center
        = f.submit 'Save and Continue', {class: 'btn btn-default mb-200', style: 'margin-bottom: 70px;'}

app/views/checkout/index.html.haml
%h1.mt-0.mb-25= t('.my_orders')
%p.in-grey-600.small.mb-10.visible-xs= t('.sort_by')
.dropdown.general-order-dropdown.mb-20
  %a.dropdown-toggle.dropdown-btn.width-100{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}
    = "#{params[:name_sort_order] || 'All'}"
    %i.fa.fa-angle-down.dropdown-icon
  %ul.dropdown-menu
    %li
      = link_to t('.all'), checkout_index_path(name_sort_order: t('.all')), method: "get"
    %li
      = link_to t('.in_queue'), checkout_index_path(sort_order: 'in_queued', name_sort_order: t('.in_queue')), method: "get"
    %li
      = link_to t('.in_delivery'), checkout_index_path(sort_order: 'in_delivering', name_sort_order: t('.in_delivery')), method: "get"
    %li
      = link_to t('.delivered'), checkout_index_path(sort_order: 'delivering', name_sort_order: t('.delivered')), method: "get"
    %li
      = link_to t('.canceled'), checkout_index_path(sort_order: 'canceling', name_sort_order: t('.canceled')), method: "get"
.visible-xs
  .general-cart-item.divider-lg-bottom.pt-0
    %table.table
      - @orders.each do |order|
        %tr
          %td.col-half
            %span.in-grey-600= t('.number')
          %td.col-half
            %span.general-order-number= order.decorate.number
        %tr
          %td
            %span.in-grey-600= t('.completed_at')
          %td
            %span.in-grey-900.font-16.font-weight-light= order.decorate.date
        %tr
          %td
            %span.in-grey-600= t('.status')
          %td
            %span.font-16.in-grey-900.font-weight-light= order.state
        %tr
          %td
            %span.in-grey-600= t('.total')
          %td
            %strong.font-16= number_to_currency(order.subtotal)
  .general-cart-item
.hidden-xs.mb-res-50
  %table.table.table-hover
    %thead
      %tr
        %th
          %span.in-grey-600= t('.number')
        %th
          %span.in-grey-600= t('.completed_at')
        %th
          %span.in-grey-600= t('.status')
        %th
          %span.in-grey-600= t('.total')
    %tbody
      - @orders.each do |order|
        %tr
          %td
            %span.general-order-number= order.decorate.number
          %td
            %span.in-grey-900.font-16.font-weight-light= order.decorate.date
          %td
            %span.font-16.font-weight-light.text-success= order.state
          %td
            %strong.font-16= number_to_currency(order.subtotal) 
 

app/views/checkout/payment.html.haml
%h1.general-title-margin= t('.checkout')
%ul.steps.list-inline
  %li.step.active
    %span.step-number
      %i.fa.fa-check.step-icon
    %span.step-text.hidden-xs= t('.address')
  %li.step-divider
  %li.step.active
    %span.step-number
      %i.fa.fa-check.step-icon
    %span.step-text.hidden-xs= t('.delivery')
  %li.step-divider
  %li.step.active
    %span.step-number 3
    %span.step-text.hidden-xs= t('.payment')
  %li.step-divider
  %li.step
    %span.step-number 4
    %span.step-text.hidden-xs= t('.confirm')
  %li.step-divider
  %li.step
    %span.step-number 5
    %span.step-text.hidden-xs= t('.complete')
%h3.general-subtitle= t('.credit_card')
= form_for @card, :url => checkout_path(step: :payment, next_render: :confirmation), :method => :put, :html => { :class => 'max-600 mb-80'} do |f|
  .form-group{class: "#{"has-error" if card_has_error?(:card_number)}"}
    = f.label :card_number, t('.card_number'), { class: 'control-label font-weight-lights', for: "cardNumber" }
    = f.text_field :card_number, { class: 'form-control', id: 'cardNumber', type: "text", name: "card_number", placeholder: "Card Number" }
    %span.help-block= card_error_message(:card_number) if @card.errors.any?
  .row
    .col-sm-6
      .form-group{class: "#{"has-error" if card_has_error?(:name_on_card)}"}
        = f.label :name_on_card, t('.name_on_card'), { class: 'control-label font-weight-lights', for: "cardName" }
        = f.text_field :name_on_card, { class: 'form-control', id: 'cardName', type: "text", name: "name_on_card", placeholder: "Name on Card" }
        %span.help-block= card_error_message(:name_on_card) if @card.errors.any?
    .col-sm-3
      .form-group{class: "#{"has-error" if card_has_error?(:mm_yy)}"}
        = f.label :mm_yy, t('.mm_yy'), { class: 'control-label font-weight-lights', for: "firstName" }
        = f.text_field :mm_yy, { class: 'form-control', id: 'firstName', name: "mm_yy", type: "text", placeholder: "MM / YY" }
        %span.help-block= card_error_message(:mm_yy) if @card.errors.any?
    .col-sm-3
      .form-group.relative{class: "#{"has-error" if card_has_error?(:cvv)}"}
        = f.label :cvv, t('.cvv'), { class: 'control-label font-weight-lights', for: "cvv" }
        = f.text_field :cvv, { class: 'form-control', id: 'cvv', name: "cvv", type: "text", placeholder: "CVV" }
        %i.fa.fa-question-circle.general-form-help.font-18
        <a href="#" title="The CVV number (Card Verification Value) on a credit card is a 3-4 digit number on VISA, MasterCard" class="fa fa-question-circle general-form-help font-18" style="text-decoration: none;"></a>
        %span.tooltip
        %span.help-block= card_error_message(:cvv) if @card.errors.any?
      .form-group.relative
  .general-text-align
  %p.in-gold-500.font-18= t('.order_total')
  %table.general-summary-table
    %tr
      %td
        %p.font-16= t('.subtotal')
      %td
        %p.font-16= number_to_currency(@order.total_price + @order.delivery&.price.to_i)
    %tr
      %td
        %p.font-16= t('.coupon') 
      %td
        %p.font-16= number_to_currency(@order.coupon&.price.to_i)
    %tr
      %td
        %strong.font-18= t('.order_total')
      %td
        %strong.font-18= number_to_currency(@order.total_price + @order.delivery&.price.to_i - @order.coupon&.price.to_i)
  .text-center
    = f.submit 'Save and Continue', {class: 'btn btn-default mb-80'}