config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  authenticate :user, lambda { |u| u.role?(:admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end

  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '(:locale)' do
    resources :checkout, only: %i[show edit update]
    resources :order_items, only: %i[create update destroy]
    resources :carts, only: %i[show update]
    resources :orders, only: %i[index show]
    resource :product, only: %i[show] do
      resources :comments, only: %i[index create]
    end
    resources :settings, only: %i[index create destroy]
    resource :settings, only: %i[update] do
      collection do
        patch 'update_password'
      end
    end

    root 'pages#home', as: 'store', via: :all

    get '/', to: 'pages#home', as: 'home'
    get '/catalog', to: 'pages#catalog', as: 'catalog'
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :authenticate_user!

  def index
    @billing_address = set_billing_address
    @shipping_address = set_shipping_address
  end

  def create
    form_address(params)
    if save_address
      redirect_to settings_path(user_id: current_user.id)
    else
      render :index
    end
  end

  def update_password
    if current_user.update(user_params)
      bypass_sign_in(current_user)
      redirect_to store_path
    else
      redirect_to settings_path(params)
    end
  end

  def destroy
    current_user.soft_delete
    sign_out
    redirect_to after_sign_out_path_for(:user)
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :reset_password_token)
  end

  def set_billing_address
    current_user.addresses.billing.last || current_user.addresses.billing.new
  end

  def set_shipping_address
    current_user.addresses.shipping.last || current_user.addresses.shipping.new
  end

  def form_address(params)
    return @billing_address = AddressForm.new(params[:billing].permit!) if params[:billing]

    @shipping_address = AddressForm.new(params[:shipping].permit!) if params[:shipping]
  end

  def save_address
    if @billing_address
      @shipping_address = set_shipping_address
      @billing_address.save
    else
      @billing_address = set_billing_address
      @shipping_address.save
    end
  end
end

app/views/settings/_form_settings.html.haml
.row.mb-60
  .col-sm-5
    %p.in-gold-500.font-18.mb-25= t('.email')
    .general-text-align
    = form_for( current_user, :url => update_password_settings_path(user_id: current_user.id), :method => :patch, html: { :class => 'general-form-md'} ) do |f|
      .form-group.mb-35
        = f.label :email, 'Enter Email', { class: 'control-label font-weight-lights', for: "email" }
        = f.text_field :email, { class: 'form-control', id: 'email', type: "email", placeholder: "Enter your email" }
      .general-text-align
        = f.submit 'Save', {class: 'btn btn-default mb-35'}
  .col-sm-5.col-sm-offset-1
    %p.in-gold-500.font-18.mb-25= t('.password')
    = form_for(current_user, as: :user, url: update_password_settings_path(user_id: current_user.id), html: { method: :patch, class: "general-form" }) do |f|
      = f.hidden_field :reset_password_token
      .form-group.mb-30
        %label.control-label.font-weight-light{for: "password"}= t('.type_a_new_password')
        = f.password_field :password, autofocus: true, autocomplete: "off", placeholder: "Type a new Password", id: "password", class: "form-control"
      .form-group.mb-40
        %label.control-label.font-weight-light{for: "confirmPassword"}= t('.confirm_password')
        = f.password_field :password_confirmation, autocomplete: "off", placeholder: "Confirm Password", id: "confirmPassword", class: "form-control"
      .actions
        = f.submit "Change", class: "btn btn-default center-block mb-20"
  .col-sm-12
    .divider-lg-bottom
    %p.in-gold-500.font-18.mb-25.pt-20= t('.remove_account')
    %form
      .general-settings-btn
        = link_to t('.remove_account'), setting_path(current_user), class: 'btn btn-default remove-btn mb-20', method: :delete, id: "removeBtn"
      .form-group.checkbox.general-settings-checkbox
        %label.font-weight-light.pl-0

app/views/settings/index.html.haml
%h1.general-title-margin= t('.settings')
%ul.nav.nav-tabs.mb-20{role: "tablist"}
  %li.mb-10.active{role: "presentation"}
    %a{href: "#address", 'aria-controls': "address", role: "tab", 'data-toggle': "tab"}= t('.address')
  %li.mb-10{role: "presentation"}
    %a{href: "#privacy", 'aria-controls': "privacy", role: "tab", 'data-toggle': "tab"}= t('.privacy')
.tab-content
  #address.tab-pane.fade.in.active.general-main-wrap{role: "tabpanel"}
    .hidden-xs.hidden-sm
      .row
        .col-md-5 
          %h3.general-subtitle= t('.billing_address')
          %p.general-info-text= t('.all_fields_are_required')
        .col-md-5.col-md-offset-1
          %h3.general-subtitle= t('.shipping_address')
          %p.general-info-text= t('address.all_fields_required')
    .row
      .col-md-5.mb-40
        = form_for @billing_address, :url => settings_path(user_id: current_user.id, id: current_user.id), :method => :post do |f|
          = render partial: 'checkout/address_form', locals: { address: @billing_address, address_type: :billing, order: false }
          = f.submit I18n.t('save_and_continue'), { class: 'btn center-block mb-20' }
      .col-md-5.col-md-offset-1.mb-60#form2{style: "#{'display: none;' if check?}" }
        = form_for @shipping_address, :url => settings_path(user_id: current_user.id, id: current_user.id), :method => :post do |f|
          = render partial: 'checkout/address_form', locals: { address: @shipping_address, address_type: :shipping, order: false }
          = f.submit I18n.t('save_and_continue'), { class: 'btn center-block mb-20' }
      .col-md-5.mb-40
      .col-md-5.col-md-offset-1.mb-60
#privacy.tab-pane.fade{role: "tabpanel"}
  = render 'form_settings'