config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  authenticate :user, lambda { |u| u.role?(:admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end

  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '(:locale)' do
    resources :checkout, only: %i[show edit update]
    resources :order_items, only: %i[create update destroy]
    resources :carts, only: %i[show update]
    resources :orders, only: %i[index show]
    resource :product, only: %i[show] do
      resources :comments, only: %i[index create]
    end
    resources :settings, only: %i[index create destroy]
    resource :settings, only: %i[update] do
      collection do
        patch 'update_password'
      end
    end

    root 'pages#home', as: 'store', via: :all

    get '/', to: 'pages#home', as: 'home'
    get '/catalog', to: 'pages#catalog', as: 'catalog'
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :read, :all
    return unless user.persisted?

    can %i[index show update edit], :order
    can :manage, User, id: user.id
    can :manage, Order, user_id: user.id
    can :create, Comment
    return unless user.role == 'admin'

    can :read, ActiveAdmin::Page, namespace_name: :admin
    can :manage, :all
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true

  enum address_type: %i[billing shipping]

  scope :search_billing, -> { where(address_type: :billing) }
  scope :search_shipping, -> { where(address_type: :shipping) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :author_products
  has_many :products, through: :author_products

  validates :first_name, :last_name, presence: true
end

app/models/author_product.rb
class AuthorProduct < ApplicationRecord
  belongs_to :author
  belongs_to :product

  self.primary_key = 'author_id'
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :order
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy

  validates :category, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  include AASM

  belongs_to :user
  belongs_to :product

  attr_accessor :active_admin_requested_event

  scope :approved, -> { where("approved = 'approved'").order(created_at: :desc) }

  validates :rate, :title, :body, presence: true
  validates_inclusion_of :rate, in: 1..5

  validates :title, length: { maximum: 80 }
  validates :body, length: { maximum: 500 }

  aasm column: 'approved', whiny_transitions: false do
    state :unprocessed, initial: true
    state :approved, :rejected

    event :approve do
      transitions from: :unprocessed, to: :approved
    end

    event :reject do
      transitions from: :unprocessed, to: :rejected
    end

    event :unprocess do
      transitions from: %i[rejected approved], to: :unprocessed
    end
  end
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  has_many :orders
end

app/models/cover.rb
class Cover < ApplicationRecord
  belongs_to :product

  mount_uploader :image_url, FileUploader
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  has_many :orders
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  def total_price
    self.product.price * self.quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM

  attr_accessor :active_admin_requested_event

  belongs_to :user, optional: true
  belongs_to :delivery, optional: true
  belongs_to :coupon, optional: true
  belongs_to :card, optional: true
  has_many :addresses, as: :addressable
  has_many :order_items

  scope :active_order, ->(order_id) {
    where(state: %i[cart address delivery_method payment confirmation complete]).find(order_id)
  }
  scope :sort_order, ->(user_id, sort_order = nil) {
    where(user_id: user_id)
      .where(state: sort_order || %i[in_queued in_delivering delivering canceling])
      .order(id: :desc)
  }

  aasm column: 'state' do
    state :cart, initial: true
    state :complete
    state :in_queued
    state :in_delivering
    state :delivering
    state :canceling

    event :add_complete do
      transitions from: :cart, to: :complete
    end

    event :add_in_queued do
      transitions from: :complete, to: :in_queued
    end

    event :in_delivery do
      transitions from: :in_queued, to: :in_delivering
    end

    event :end_delivery do
      transitions from: :in_delivering, to: :delivering
    end

    event :cancel do
      transitions from: %i[in_queued in_delivering delivering], to: :canceling
    end
  end

  def total_price
    order_items.sum(&:total_price)
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  def total_price
    product.price * quantity
  end

  validates :quantity, numericality: { greater_than_or_equal_to: 0 }
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items
  has_many :author_products
  has_many :authors, through: :author_products
  has_many :covers, dependent: :destroy
  belongs_to :category

  accepts_nested_attributes_for :covers, allow_destroy: true

  scope :latest_products, ->(latest_default_quantity) { Product.last(latest_default_quantity) }
  scope :sort_column, ->(context) {
    Product.column_names.include?(context.params[:sort]) ? context.params[:sort] : 'created_at'
  }
  scope :sort_direction, ->(context) {
    %w[asc desc].include?(context.params[:direction]) ?  context.params[:direction] : 'desc'
  }
  scope :sort_product, ->(context) {
    order(sort_column(context) + ' ' + sort_direction(context)).where(category_id: context.category_id)
  }
end

app/models/user.rb
require 'letter_avatar/has_avatar'

class User < ApplicationRecord
  include LetterAvatar::HasAvatar
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :omniauthable, omniauth_providers: [:facebook]

  has_many :orders
  has_many :comments, dependent: :destroy
  has_many :addresses, as: :addressable, dependent: :destroy

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.pictures = auth.info.image
      user.save
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if (data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info'])
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def role?(rol)
    role ? (role.include? rol.to_s) : false
  end

  def soft_delete
    update_attribute(:deleted_at, Time.current)
  end

  def name
    addresses.billing.last.last_name
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    redirect_to store_url if check_order_items?
  end

  def update
    coupon = Coupon.find_by(number: coupon_params)
    if coupon && coupon.id != 1
      @order.update(coupon: coupon)
    else
      flash[:message] = t('.no_coupon')
    end
    redirect_to cart_path
  end

  private

  def check_order_items?
    @order.order_items.empty?
  end

  def coupon_params
    params.require(:order).permit(:number).dig(:number).to_i
  end
end

app/controllers/home_controller.rb
require_dependency './app/queries/bestsellers.rb'
class HomeController < ApplicationController
  def show
    @slide = Product.slide
    @product = Bestsellers.call
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def adress_has_error?(address, field)
    address.errors.include?(field)
  end

  def adress_error_message(address, field)
    address.errors.messages[field].first
  end

  def card_has_error?(field)
    @card.errors.include?(field)
  end

  def card_error_message(field)
    @card.errors.messages[field].first
  end

  def check?
    if session[:check] == 'true'
      true
    elsif session[:check] == 'false'
      false
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
  include Pagy::Frontend
end

app/views/admin/covers/_form.html.haml
= semantic_form_for [:admin, @cover], builder: ActiveAdmin::FormBuilder do |f|
  = f.inputs do
    = f.input :product_id
    = f.input :image_url, as: :file
    = f.actions

app/views/carts/show.html.haml
%h1.general-title-margin= t('.cart')
.hidden-xs
  %table.table.table-hover
    %tr.no-hover
      %th.col-pic.pl-0
        %span.in-grey-600= t('.product')
      %th.col-title
      %th.col-price
        %span.in-grey-600= t('.price')
      %th.col-quantity
        %span.in-grey-600= t('.quantity')
      %th.col-total
        %span.in-grey-600= t('.subtotal')
      %th.col-close
    - @order.order_items.each do |item|
      %tr
        %td
          .general-img-wrap-table
            %img.cart-img-shadow.pull-left.width-full{src: item.product.covers.first&.image_url}
        %td
          %p.general-title= item.product.title
        %td
          %span.font-16.in-gold-500= "€#{item.product.price}"
        %td
          .input-group
            = link_to order_item_path(item, type: OrderItemsController::COMMANDS[:delete], redirect_to: cart_path(@order)), method: :patch, class: "input-link" do
              %i.fa.switchers.fa-minus.line-height-40
            %input.form-control.quantity-input{:type => "text", :value => item.quantity, readonly: true}
            = link_to order_item_path(item, type: OrderItemsController::COMMANDS[:add], redirect_to: cart_path(@order)), method: :patch, class: "input-link" do
              %i.fa.switchers.fa-plus.line-height-40
        %td
          %span.font-16.in-gold-500= number_to_currency(item.total_price)
        %td
          = button_to order_item_path(item), method: :delete, class: 'close general-cart-close' do
            %span{'aria-hidden': 'true'} &times;
.general-order-wrap
  .row
    .col-sm-4
      .flash.text-center
        - flash.each do |message_type, message|
          %div{ class: "text-danger alert alert-#{message_type}" }
            = message
      = form_for :order, url: cart_path, method: :patch do |f|
        = f.label :number, t('.enter_your_coupon_code'), { class: 'font-weight-light', for: "number" }
        = f.text_field :number, { class: 'form-control mb-30', type: "text", placeholder: "Enter Your Coupon Code", value: '' }
        = f.submit t('.update_cart'), {class: 'btn btn-primary mb-15 res-block'}
    .col-sm-8
      .res-mr-200.text-center.general-text-right
        %p.in-gold-500.font-18= t('.order_summary')
        %table.general-summary-table.general-summary-table-right.general-text-right
          %tr
            %td
              %p.font-16= t('.subtotal')
            %td
              %p.font-16= number_to_currency(@order.total_price)
          %tr
            %td
              %p.font-16= t('.coupon')
            %td
              %p.font-16= number_to_currency(@order.coupon&.price)
          %tr
            %td
              %strong.font-18= t('.order_total')
            %td
              %strong.font-18= number_to_currency(@order.total_price - (@order.coupon&.price || 0))
        %button.btn.btn-default.mb-20.visible-xs-inline-block= t('.checkout')
= button_to t('.checkout'), checkout_path, method: :get, class: 'btn btn-default mb-20 hidden-xs center-block', params: { next_render: :address, step: :address }

app/views/home/index.html.haml
#slider.carousel.slide{'data-ride': "carousel"}
  %ol.carousel-indicators.general-carousel-indicators
    %li.active{'data-target': "#slider", 'data-slide-to': "0"}
    %li{'data-target': "#slider", 'data-slide-to': "1"}
  .carousel-inner{role: "listbox"}
    - @slide.each_index do |i|
      .item{class: ("active" if i == 0)}
        .row
          .col-sm-5
            .general-img-wrap 
              %img.img-shadow.general-thumbnail-img.width-full{src: @slide[i].image, alt: "design-book"}
          .col-sm-7
            .mb-60
              %h1= @slide[i].title
              %p.lead= @slide[i].description
              %p.in-grey-600.small= "#{@slide[i].author.first_name} #{@slide[i].author.last_name}"
              .general-align.pt-20
                = button_to 'Buy Now', home_index_path(product_id: @slide[i]), method: "post", class: "btn"
  %a.left.carousel-control{href: "#slider", role: "button", 'data-slide': "prev"}
    %span.icon-prev{'aria-hidden': "true"}
    %span.sr-only= t('.previous')
  %a.right.carousel-control{href: "#slider", role: "button", 'data-slide': "next"}
    %span.icon-next{'aria-hidden': "true"}
    %span.sr-only= t('.next')
.container
.jumbotron.text-center.mb-0
  %h2.h1= t('.welcome')
  .mb-res-50
    %p.in-grey-600= t('.we_pore')
  = button_to 'Get Started', product_path, method: "get", class: "btn btn-default"
.mb-35
  %h3= t('.best_sellers')
  .row
    - @product.each do |product|
      .col-sm-6.col-md-3
        .general-thumb-wrap
          .thumbnail.general-thumbnail
            %img.img-shadow.general-thumbnail-img{src: product.image, alt: "design-book"}
            .thumb-hover
              .general-thumb-link-wrap
                %a.thumb-hover-link{href: "#{book_path(id: product)}"}
                  %i.fa.fa-eye.thumb-icon{'aria-hidden': "true"}
                %a.thumb-hover-link{href: "#{line_items_path(product_id: product)}"} 
                  %i.fa.fa-shopping-cart.thumb-icon
        .mb-35
          .clearfix
            %p.pull-right.font-16.in-gold-500= number_to_currency(product.price)
            %p.general-title.mr-55= product.title
          %span.divider-sm
          %p.in-grey-600.small= "#{product.author.first_name} #{product.author.last_name}" 