config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  authenticate :user, lambda { |u| u.role?(:admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end

  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '(:locale)' do
    resources :checkout, only: %i[show edit update]
    resources :order_items, only: %i[create update destroy]
    resources :carts, only: %i[show update]
    resources :orders, only: %i[index show]
    resource :product, only: %i[show] do
      resources :comments, only: %i[index create]
    end
    resources :settings, only: %i[index create destroy]
    resource :settings, only: %i[update] do
      collection do
        patch 'update_password'
      end
    end

    root 'pages#home', as: 'store', via: :all

    get '/', to: 'pages#home', as: 'home'
    get '/catalog', to: 'pages#catalog', as: 'catalog'
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :read, :all
    return unless user.persisted?

    can %i[index show update edit], :order
    can :manage, User, id: user.id
    can :manage, Order, user_id: user.id
    can :create, Comment
    return unless user.role == 'admin'

    can :read, ActiveAdmin::Page, namespace_name: :admin
    can :manage, :all
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true

  enum address_type: %i[billing shipping]

  scope :search_billing, -> { where(address_type: :billing) }
  scope :search_shipping, -> { where(address_type: :shipping) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :author_products
  has_many :products, through: :author_products

  validates :first_name, :last_name, presence: true
end

app/models/author_product.rb
class AuthorProduct < ApplicationRecord
  belongs_to :author
  belongs_to :product

  self.primary_key = 'author_id'
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :order
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy

  validates :category, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  include AASM

  belongs_to :user
  belongs_to :product

  attr_accessor :active_admin_requested_event

  scope :approved, -> { where("approved = 'approved'").order(created_at: :desc) }

  validates :rate, :title, :body, presence: true
  validates_inclusion_of :rate, in: 1..5

  validates :title, length: { maximum: 80 }
  validates :body, length: { maximum: 500 }

  aasm column: 'approved', whiny_transitions: false do
    state :unprocessed, initial: true
    state :approved, :rejected

    event :approve do
      transitions from: :unprocessed, to: :approved
    end

    event :reject do
      transitions from: :unprocessed, to: :rejected
    end

    event :unprocess do
      transitions from: %i[rejected approved], to: :unprocessed
    end
  end
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  has_many :orders
end

app/models/cover.rb
class Cover < ApplicationRecord
  belongs_to :product

  mount_uploader :image_url, FileUploader
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  has_many :orders
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  def total_price
    self.product.price * self.quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM

  attr_accessor :active_admin_requested_event

  belongs_to :user, optional: true
  belongs_to :delivery, optional: true
  belongs_to :coupon, optional: true
  belongs_to :card, optional: true
  has_many :addresses, as: :addressable
  has_many :order_items

  scope :active_order, ->(order_id) {
    where(state: %i[cart address delivery_method payment confirmation complete]).find(order_id)
  }
  scope :sort_order, ->(user_id, sort_order = nil) {
    where(user_id: user_id)
      .where(state: sort_order || %i[in_queued in_delivering delivering canceling])
      .order(id: :desc)
  }

  aasm column: 'state' do
    state :cart, initial: true
    state :complete
    state :in_queued
    state :in_delivering
    state :delivering
    state :canceling

    event :add_complete do
      transitions from: :cart, to: :complete
    end

    event :add_in_queued do
      transitions from: :complete, to: :in_queued
    end

    event :in_delivery do
      transitions from: :in_queued, to: :in_delivering
    end

    event :end_delivery do
      transitions from: :in_delivering, to: :delivering
    end

    event :cancel do
      transitions from: %i[in_queued in_delivering delivering], to: :canceling
    end
  end

  def total_price
    order_items.sum(&:total_price)
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  def total_price
    product.price * quantity
  end

  validates :quantity, numericality: { greater_than_or_equal_to: 0 }
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items
  has_many :author_products
  has_many :authors, through: :author_products
  has_many :covers, dependent: :destroy
  belongs_to :category

  accepts_nested_attributes_for :covers, allow_destroy: true

  scope :latest_products, ->(latest_default_quantity) { Product.last(latest_default_quantity) }
  scope :sort_column, ->(context) {
    Product.column_names.include?(context.params[:sort]) ? context.params[:sort] : 'created_at'
  }
  scope :sort_direction, ->(context) {
    %w[asc desc].include?(context.params[:direction]) ?  context.params[:direction] : 'desc'
  }
  scope :sort_product, ->(context) {
    order(sort_column(context) + ' ' + sort_direction(context)).where(category_id: context.category_id)
  }
end

app/models/user.rb
require 'letter_avatar/has_avatar'

class User < ApplicationRecord
  include LetterAvatar::HasAvatar
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :omniauthable, omniauth_providers: [:facebook]

  has_many :orders
  has_many :comments, dependent: :destroy
  has_many :addresses, as: :addressable, dependent: :destroy

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.pictures = auth.info.image
      user.save
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if (data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info'])
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def role?(rol)
    role ? (role.include? rol.to_s) : false
  end

  def soft_delete
    update_attribute(:deleted_at, Time.current)
  end

  def name
    addresses.billing.last.last_name
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    redirect_to store_url if check_order_items?
  end

  def update
    coupon = Coupon.find_by(number: coupon_params)
    if coupon && coupon.id != 1
      @order.update(coupon: coupon)
    else
      flash[:message] = t('.no_coupon')
    end
    redirect_to cart_path
  end

  private

  def check_order_items?
    @order.order_items.empty?
  end

  def coupon_params
    params.require(:order).permit(:number).dig(:number).to_i
  end
end

app/controllers/home_controller.rb
require_dependency './app/queries/bestsellers.rb'
class HomeController < ApplicationController
  def show
    @slide = Product.slide
    @product = Bestsellers.call
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource

  def show
    @product = Product.find(params[:id]).decorate
    @reviews = Comment.where(product_id: params[:id], approved: true)
    save_my_previous_url
  end

  private

  def save_my_previous_url
    session[:return_to] ||= request.referer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def adress_has_error?(address, field)
    address.errors.include?(field)
  end

  def adress_error_message(address, field)
    address.errors.messages[field].first
  end

  def card_has_error?(field)
    @card.errors.include?(field)
  end

  def card_error_message(field)
    @card.errors.messages[field].first
  end

  def check?
    if session[:check] == 'true'
      true
    elsif session[:check] == 'false'
      false
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
  include Pagy::Frontend
end

app/views/admin/products/_show.html.haml
.row
  .col-sm-6
    .product-gallery
      .mb-20#img_container
        %img.img-responsive{src: @product.covers.first&.image_url}
      %p
      .images.clearfix
        - @product.covers.each do |picture|
          %a.img-link{href: "#"}
            %img.width-full.height-preview{src: picture.image_url}
  .col-sm-6
    %h1.mt-res-0.row-bordered= @product.title
    .card.row-bordered
      %h4= t('.authors')
      %p.in-grey-600.small= @product.authors.map { |author| "#{author.first_name} #{author.last_name}" }.join(', ')
    .card.row-bordered
      %p.h1.in-gold-500.mt-10= number_to_currency(@product.price, unit: '€')
    .card.row-bordered
      %h4= t('.description')
      %p.in-grey-600.small.line-height-2
        = @product.description
      %h4= t('.materials')
      %p.in-grey-600.small.line-height-2
        = @product.materials

app/views/products/_form_review.html.haml
= form_for(@product.comments.build, url: product_comments_path, :method => :post) do |f|
  .hidden-xs.hidden-sm
    .row
      .col-md-8
        %h4.general-subtitle.mb-20= t('.write_a_review')
  .row
    .col-md-8.mb-40
      .visible-xs.visible-sm
        %h3.general-subtitle.mt-0= t('.write_a_review')
      .form-group.mb-20
        %label.control-label.font-weight-light.in-grey-600{for: :rate}= t('.rating')
        .rating.form-group.mb-15
          - 5.times do |rate|
            %label
              = f.radio_button :rate, "#{rate + 1}"
              %i.fa.fa-star
        %span.help-block
      .form-group
        %label.control-label.font-weight-light.in-grey-600{for: :body}= t('.review')
        = f.hidden_field :product_id, value: @product.id
        = f.hidden_field :user_id, value: current_user.id
        = f.text_field :title, required: true, class: 'form-control', placeholder: 'title', maxlength: 80
        %span.help-block
        = f.text_area :body, required: true, class: 'form-control', placeholder: 'body', maxlength: 500
        %span.help-block
      = f.submit "Post", class: 'btn pull-right'
  

app/views/products/_show_review.html.haml
.mb-80
  %h3.in-gold-500.mb-25= "Reviews (#{@product.comments.approved.count})"
  %ul.media-list
    - @product.comments.approved.each do |comment|
      - comment.rate
      %li.media.card
        .media-left
          %img.img-circle.logo-size.media-object{src: "#{ comment.user.pictures || comment.user.avatar_url(200) }"}
        .media-body
          %div
            %p.general-message-date.hidden-xs= comment.created_at
            %h4.media-heading.max-240.general-message-name
            .in-gold-500.media-left
              = comment.user.email
          .mb-15
            - 5.times.collect do |i|
              %i.fa.fa-star.rate-star{:class => ('rate-empty' if i >= comment.rate)}
          %p= comment.title
          %p= comment.body
            

app/views/products/show.html.haml
%a.general-back-link{href:"#{session.delete(:return_to)}"}
  %i.fa.fa-long-arrow-left.mr-15
  = t('.back_to_results')
.row
  .col-sm-6
    .product-gallery
      .mb-20
        %img.img-responsive.imgv{src: @product.image}
      .images.clearfix
        %a.img-link{href: "#"}
          %img.width-full{src: @product.image}
        %a.img-link{href: "#"}
          %img.width-full{src: @product.image}
        %a.img-link{href: "#"}
          %img.width-full{src: @product.image}
  .col-sm-6
    %h1.mt-res-0= @product.title
    %p.in-grey-600.small= @product.author_name
    .row
      .col-xs-12.col-md-4
        %p.h1.in-gold-500.mt-10= @product.price
      .col-xs-5.col-md-3
        = form_tag(order_items_path, method: "post")
        .input-group.general-position
          %a.input-link.minus.fa.fa-minus.line-height-40.help_fa{href: ""}
          %input.form-control.quantity-input{id: "quantity", type: "text", name: "quantity", min: 1, max: 999, value: 1}
          %input.form-control.quantity-input.hidden{type: "text", name: "id", value: "#{@product.id}"}
          %input.form-control.quantity-input.hidden{type: "text", name: "product_id", value: "#{@product.id}"}
          %input.form-control.quantity-input.hidden{type: "text", name: "order_id", value: "#{@order.id}"}
          %input.form-control.quantity-input.hidden{type: "text", name: "redirect_to", value: "#{product_path(id: @product.id)}"}
          %a.input-link.plus.fa.fa-plus.line-height-40.help_fa{href: ""}
          %input.btn.btn-default.pull-right.general-positionid.hidden{id: '1', type: "submit", value: t('.add_to_cart')}
      .col-xs-7.col-md-5
        %button.btn.btn-default.pull-right.general-position{type: "submit", id: 'add-to-cart', onclick: "document.getElementById('1').click()"}= t('.add_to_cart')
        .hidden
          = button_to t('.add_to_cart'), {type: "submit", class: 'btn btn-default pull-right general-position hidden', onclick: "document.getElementById('1').click()"}
    .card
      %p= t('.description')
      %p.lead.small.line-height-2
        - if @product.description.length >= 250
          = truncate(@product.description, length: 250)
          = link_to t('.read_more'), '', class: 'in-gold-500 ml-10 read-more'
          :javascript
            $('.read-more').on('click', function(e) {
              e.preventDefault();
              $(this).parent().html("#{@product.description}")
            })
        - else
          = @product.description
    .card
      .clearfix
        %p.general-item-info.pull-right= @product.date
        %p.break-word= t('.year_of_publication')
    .card
      .clearfix
        %p.general-item-info.pull-right= @product.dimensions
        %p.break-word= t('.dimensions')
    .card
      .clearfix
        %p.general-item-info.pull-right= @product.materials
        %p.break-word= t('.materials')
.mb-80
  %ul.media-list
    = render 'products/show_review'
    - if user_signed_in?
      = render 'products/form_review' 